### ISSUE TITLE
not able compile ved on windows 10 

### ISSUE THREAD

**Issue by ramanandapanda** [vlang/ved#111]
getting error while compiling the ved on windows 10

.\ved.v:650:7: warning: function `utf32_to_str_no_malloc` must be called from an `unsafe` block
  648 |     }
  649 |     buf := [0, 0, 0, 0, 0]
  650 |     s := utf32_to_str_no_malloc(code, buf) // .data)
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  651 |     // s := utf32_to_str(code)
  652 |     // println('s="$s" code="$code"')

**Comment by serkonda7** [comment]
Fixed in recent versions.
