### ISSUE TITLE
Install Ved

### ISSUE THREAD

**Issue by vinothkumar64** [vlang/ved#159]
Can you tell me how to install Ved in my archlinux system...

**Comment by johhnry** [comment]
Hi,

You should [build it from source](https://github.com/vlang/ved#building-from-source) after installing the V language compiler.

**Comment by vinothkumar64** [comment]
I compiled How I install my local system

**Comment by vinothkumar64** [comment]
> Hi,
> 
> You should [build it from source](https://github.com/vlang/ved#building-from-source) after installing the V language compiler.


I compiled how do I call install my local system.

**Comment by johhnry** [comment]
You can either make a symlink to [`/usr/local/bin`](https://unix.stackexchange.com/a/8658) to make it accessible globally or depending on your desktop manager, add a launcher icon (for example in Gnome, [adding a Desktop Entry](https://wiki.archlinux.org/title/desktop_entries))

**Comment by vinothkumar64** [comment]
> You can either make a symlink to [`/usr/local/bin`](https://unix.stackexchange.com/a/8658) to make it accessible globally or depending on your desktop manager, add a launcher icon (for example in Gnome, [adding a Desktop Entry](https://wiki.archlinux.org/title/desktop_entries))

Thanks for the support 🙂
