### ISSUE TITLE
On wayland it is full screened

### ISSUE THREAD

**Issue by Jeremy-JYL** [vlang/ved#186]
I have a Macbook Air with Asahi Linux on it because ved is not working on macos but I don't know is the V problem or ved problem it keep ask me X11 lib so I install them. But open it, it is full screen is there any way to make it a window app and make this to a wayland app.

**Comment by medvednikov** [comment]
macOS is my main OS, so it works best on it. What happens on macOS for you?

try `./ved -window` to avoid full screen

**Comment by Jeremy-JYL** [comment]
I have the issue in 184 on Macos
