### ISSUE TITLE
Can't go to end of line

### ISSUE THREAD

**Issue by Henrixounez** [vlang/ved#22]
Can't go further than one character behind, thus can't add to the end of a line.

**Comment by JalonSolov** [comment]
In current ved, move cursor to the line you want to add onto, then hit `Shift-A`.  This will move the cursor one position past the previous last character (no matter where the cursor was on the line when you hit `Shift-A`, and put you in insert mode, so you can add whatever you wish.

There are other keys to allow inserting at the current cursor position, etc.
