### ISSUE TITLE
V error: C error. This should never happen

### ISSUE THREAD

**Issue by whatevergeek** [vlang/ved#43]
Encountered the following issue when building and filing as advised:
Feel free to rename the issue name.

warning: use "_linux.v" file name instead of "/home/username/sandbox/v_stuff/v/vlib/ui/ui_lin.v"
warning: ./vid.v:5:6: the following imports were never used:
 * gx                                                                                   tcc: arm64-gen.c:1726: gen_cvt_ftof: Assertion `f == VT_FLOAT || f == VT_DOUBLE || f ==VT_LDOUBLE' failed.                                                                      Aborted
V error: C error. This should never happen.                                             Please create a GitHub issue: https://github.com/vlang/v/issues/new/choose

**Comment by JalonSolov** [comment]
Latest ved compiles and runs clean with latest version of V.
