### ISSUE TITLE
error adding symbols: File in wrong format collect2.exe: error: ld returned 1 exit status V error: C error. This should never happen.

### ISSUE THREAD

**Issue by linia** [vlang/ved#49]
error adding symbols: File in wrong format
collect2.exe: error: ld returned 1 exit status
V error: C error. This should never happen.

**Comment by linia** [comment]
win64/freetype.lib: error adding symbols: File in wrong format

**Comment by JalonSolov** [comment]
Latest version of ved compiles and runs fine on Windows 10 with latest version of V.
