### ISSUE TITLE
failed build on V 0.1.24 0d93eeb

### ISSUE THREAD

**Issue by kokizzu** [vlang/ved#60]
```
./timer.v:155:61: wrong number of arguments in call to `gg.GG*.draw_line(f32, f32, f32, f32)`
  153|                          '${hour:02d}', time_cfg)
  154|          }
  155|          t.gg.draw_line(hour_x, hour_y, hour_x + hour_width, hour_y, gx.gray)
                                                                            ^
  156|  }
  157|  // Large left vertical line
```

**Comment by yewpad** [comment]
Same here.

**Comment by zzadi** [comment]
@kokizzu , @yewpad, 

To fix this issue you may replace all the **draw_line** with **draw_line_c** in the files -  timer.v and vid.v

I have tested that on my Mac (osx 10.13.6). I can successfully build the vid after done the above replacement. But after I launch vid, I can't found any menu.

**Comment by medvednikov** [comment]
draw_line_c was removed, you have to update V and Vid.

@zzadi there are no menus, you have to open the file  with  `C-O`  or `./vid file`  or `./vid path/to/project`.

**Comment by medvednikov** [comment]
Oh, I have to update the  prebuilt package. Will do.

**Comment by zzadi** [comment]
@medvednikov noticed with thanks

**Comment by JalonSolov** [comment]
ved compiles fine with latest version of v.
