### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by kaseyhinton** [vlang/ved#61]
## High memory consumption

As I was checking out this editor I noticed what appears to be a slow memory leak. I am on windows 10 fresh install fully updated. It took about 30 minutes or so of just leaving vid up in the background to get to about 500MB. All I did was open up a file, execute a few commands, and let it run in the background while I was working on something else. Here are the screenshots

### Console
![console](https://user-images.githubusercontent.com/20712428/72587042-b45ee300-38a8-11ea-8023-80813ebf9785.PNG)

### Task Manager
![vidmemory](https://user-images.githubusercontent.com/20712428/72587247-6b5b5e80-38a9-11ea-8f02-78537550588e.PNG)

**Comment by medvednikov** [comment]
Yes, it's full of leaks, I know all the sources of them.

This will be fixed in V itself this month.

**Comment by kaseyhinton** [comment]
Thanks!

**Comment by medvednikov** [comment]
Should be open until it's fixed.

**Comment by bumbread** [comment]
Did it get fixed?

**Comment by medvednikov** [comment]
all leaks are fixed if built with `-gc boehm`

no flags will be needed with V 0.3

**Comment by medvednikov** [comment]
k
