### ISSUE TITLE
vid not working in Manjaro (Arch)

### ISSUE THREAD

**Issue by jangofett4** [vlang/ved#62]
### System Information
![image](https://user-images.githubusercontent.com/19552452/73766649-63475e00-4787-11ea-8be3-d85156573a06.png)
freetype2 and glfw-x11 is installed (couldn't find freetype6 and 'normal' glfw)

### Steps to reproduce
1. Clone and compile
```sh
$ git clone https://github.com/vlang/vid
$ cd vid
$ v .
```
2. Run
```sh
$ ./vid
```  
A fullscreen app opens and closes immediately leaving behind this log:
```
create window wnd=0x556517844fc0 ptr==0x556517843f10
Trying to load font from RobotoMono-Regular.ttf
Parçalama arızası (çekirdek döküldü) // this says segmentation fault (core halted?)
```
RobotoMono-Regular.ttf does exists in vid folder. This problem is probably caused from freetype or glfw but not entirely sure.

**Comment by jangofett4** [comment]
So I think I pinpointed where the error occurs:
![image](https://user-images.githubusercontent.com/19552452/73769005-0b125b00-478b-11ea-89a7-115081599320.png)
Not sure what 'timer' is or what this function is loading but at first line string.contains is segfaulting (seems like a v error?)

**Comment by shiipou** [comment]
I've got the same error on MacOs Catalina :

![Capture d’écran 2020-02-11 à 15 26 29](https://user-images.githubusercontent.com/38187238/74245219-f41bbd80-4ce2-11ea-8768-a9c95ec963a6.png)

freetype does not install RobotoMono-Regular.ttf

I've installed it with this font zip package but it didn't resolve anything : [https://www.wfonts.com/font/roboto-mono](https://www.wfonts.com/font/roboto-mono)

![Capture d’écran 2020-02-11 à 15 29 04](https://user-images.githubusercontent.com/38187238/74245673-ace1fc80-4ce3-11ea-81bf-c2aaca2983c0.png)

I suppose that :  in Mac you need to call `RobotoMono` font and not `RobotoMono-Regular`

**Comment by wilsonk** [comment]
Check partial solution in #63 

This seg fault isn't a problem with the font file and @jangofett4 is correct that the lines of code he highlighted are where the seg fault happens. The error is due to 'line' pointing to invalid memory on the first iteration of the for loop at line 53, but the actual problem is due to some missing files and improper checks (or defaults) imo.

**Comment by JalonSolov** [comment]
Please try again with the latest version of V.  I can't test on either Manjaro or Mac, but I just compiled ved on both Windows and Ubuntu Linux, and it compiled clean and ran fine.
