### ISSUE TITLE
vid doesn't build on Windows

### ISSUE THREAD

**Issue by solar-phobos** [vlang/ved#65]
Command `git clone --depth=1 https://github.com/ubawurinna/freetype-windows-binaries [path to v repo]/thirdparty/freetype/` was executed (of course instead of "[path to v repo]" was inserted absolute path to v repo). Output of v:
```
["strings", "strconv.ftoa", "strings", "hash.wyhash", "strconv", "os", "gx", "gg", "gx", "os", "time"]
.\timer.v:25:0: error: unknown module `freetype`
```

**Comment by B14CK313** [comment]
Also happens to me on Manjaro (Arch), same output, freetype is installed

**Comment by sergeevabc** [comment]
Err… So where do Windows users get a compiled Vid?

**Comment by JalonSolov** [comment]
ved compiles fine with latest version of V.

The only way anyone gets a compiled version (regardless of OS) at present is to clone the source and compile it.  There are no release downloads.
