### ISSUE TITLE
 error: undefined: `glfw.KEY_LEFT_SUPER` 

### ISSUE THREAD

**Issue by bagasayn** [vlang/ved#67]
.\vid.v:480:17: error: undefined: `glfw.KEY_LEFT_SUPER`
  478|             break
  479|         }
  480|         // End of /**/

  481|         if i > 0 && line[i - 1] == `*` && line[i] == `/` {
  482|             // All before */ is still a comment

**Comment by JalonSolov** [comment]
V no longers uses or includes glfw.
