### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by InfRandomness** [vlang/ved#72]
Vid segfaults whenever trying to open a folder with it, no matter how many files there are in that actual folder 

Output :
```
infrandomness@ir-pc vid]$ ./vid lolz/
['./vid', 'lolz/']
PATH="lolz/" cur_dir="/home/infrandomness/sources/vid"
load session "/home/infrandomness/.vid/session"
['lolz/1', '', '']
Segmentation fault (core dumped)
```

Environment :
OS : Fedora 32 (Thirty Two) with kernel 5.6.13-300.fc32.x86_64
V version : 0.1.27 4af4a8f
Vid version : ad1b74e
(Just tell me if you need more logs or more informations about my environment)

**Comment by medvednikov** [comment]
Fixed.
