### ISSUE TITLE
cross compile to window fails

### ISSUE THREAD

**Issue by gshields** [vlang/ved#79]
V 0.1.29 c01fd4a
gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

Expected v to cross compile

Got:
v -os windows nbody.v
/home/ghs/v/thirdparty/tcc/lib/openlibm.o not found, building it...
exec failed for thirdparty object build cmd:
x86_64-w64-mingw32-gcc   -fPIC  -c -o "/home/ghs/v/thirdparty/tcc/lib/openlibm.o" "/home/ghs/v/thirdparty/tcc/lib/openlibm.c" 
builder error: sh: 1: x86_64-w64-mingw32-gcc: not found

**Comment by JalonSolov** [comment]
This looks like something that should have been reported in the main V issues, since you don't mention ved at all.

I can confirm this is an issue, but it's in the wrong place.

**Comment by JalonSolov** [comment]
I entered https://github.com/vlang/v/issues/6331 for this.
