### ISSUE TITLE
ved frozen on start - missing fonts

### ISSUE THREAD

**Issue by louis77** [vlang/ved#81]
I've just build ved (d3c4058e), running Ubuntu 20.04.
Freetype is installed.

When I start `ved` I get the blank `ved` window with the header bar in fullscreen mode, but completely frozen. I have to SIGINT it. This is the console output:

```
$ ./ved .
FULL SCREEN=true
open multiple workspaces
./ved
load session "/home/louis/.ved/session"
failed to load font "SFNS-bold.ttf"
failed to load font "/System/Library/Fonts/SFNSMono.ttf"
failed to load font "/System/Library/Fonts/SFNSItalic.ttf"
```

![Screenshot from 2020-09-07 21-40-41](https://user-images.githubusercontent.com/1240462/92414093-0499f680-f153-11ea-9a9a-7413fd4f5bef.png)

**Comment by JalonSolov** [comment]
I just compiled and tried ved with the latest version of V.  It came up and ran fine.  The messages about fonts can be ignored - they are only available on MacOS, but it is still trying to load them for some reason.

**Comment by louis77** [comment]
I'm sorry @JalonSolov that I even reported the issue! I've just compiled ved on two other machines with Ubuntu 20.04 and had the same issue, but if it works for you, then I guess that must suffice for the rest of the world.
